### ISSUE TITLE
Add integration tests that are validated by the Dart VM

### ISSUE THREAD

**Issue by kevmoo** [angular/ts2dart#117]
Generate a Dart library using many (most?) features.

Validate:

* The Dart analyzer can parse it
* It can run - if it has a main method
* The output style conforms to [dart_style](https://github.com/dart-lang/dart_style)

**Comment by mprobst** [comment]
Hey. We have this [E2E test](../blob/master/test/e2e/helloworld.ts). That does pretty much what you're asking for, except it just uses `dart_style` to format the messed up code we're producing.

Feel free to re-open if there's something beyond that that you were looking for.
