### ISSUE TITLE
Abstract methods should have no body in Dart

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#12]
In AtScript this:

```
@ABSTRACT()
class Blah {
  @ABSTRACT()
  hello():void {}
}
```

Transpiles to this:

```
@ABSTRACT()
class Blah {
  @ABSTRACT() 
  hello() {}
}
```

The hello method should have no body.

**Comment by mprobst** [comment]
There are not abstract methods in TypeScript, there are only interfaces (which however should compile to abstract methods on abstract classes with empty bodies).

**Comment by yjbanov** [comment]
@mprobst What about abstract classes (e.g. those that partially implement an interface)? How would you like to express them? Or do you recommend that we avoid them?

**Comment by mprobst** [comment]
@yjbanov sorry, I should have been more specific: TypeScript doesn't have abstract classes either. I think between structural typing and interfaces, they might have thought you don't need them.

So when writing TS (and when converting the Angular code base), abstract base classes should be written as interfaces. I guess that'll make it a bit harder to share base method implementations.
