### ISSUE TITLE
Support const more fully

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#14]
If you have a class with const constructor, like this:

```
class Blah {
  @FINAL
  i:int;

  @CONST
  constructor(a:int) {
    this.i = a;
  }
}
```

It is correctly transpiled to:

```
class Blah {
  final int i;
  const Blah(int a): i = a;
}
```

However, there's no way to use it. This is wrong (but transpiler allows it):

```
const a = new Blah(3);
```

And this is not supported:

```
const a = const Blah(3);
```

**Comment by kevmoo** [comment]
We also need the ability to define top-level fields as final.

See `change_detection` in Angular. All of these should be final.

```dart
var keyValDiff = [
  new KeyValueChangesFactory(),
  new NullPipeFactory()
];

var iterableDiff = [
  new IterableChangesFactory(),
  new NullPipeFactory()
]; 

var defaultPipes = {
  "iterableDiff": iterableDiff,
  "keyValDiff": keyValDiff,
  "async": async
};
```

Related angular bug: https://github.com/angular/angular/issues/1485

**Comment by mprobst** [comment]
This is unrelated to `final` support, but `const` is supported through the special magic function `CONST_EXPR`. So I'm closing this issue.

@kevmoo if you think it's needed, please do open another issue for `final`.
