### ISSUE TITLE
Support destructuring

### ISSUE THREAD

**Issue by btford** [angular/ts2dart#158]
In TypeScript, I write:

```
var {x, y} = someFunc();

function someFunc() {
  return { x: 3, y: 4 };
}
```

This gets compiled to dart as:
```
var {x, y} = someFunc();

function someFunc() {
  return { 'x': 3, 'y': 4 };
}
```

But doesn't work, because dart itself does not have destructuring (see https://code.google.com/p/dart/issues/detail?id=75). It'd be nice to use intermediate value sin the mean time:

```
var temp1 = someFunc();
var x = temp1.x;
var y = temp1.y;

function someFunc() {
  return { 'x': 3, 'y': 4 };
}
```

**Comment by mprobst** [comment]
ts2dart is not clever enough to invent new free variables (`temp1` in your code) and likely won't ever be, nor should it. Also note that the resulting Dart code looks pretty ugly, some people actually do care about that a bit.

So, won't fix.

**Comment by btford** [comment]
:( but I understand
