### ISSUE TITLE
Do not create e_stack when e.stack is not used

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#168]
It results in "unused variable" warnings when the exception is simply rethrown, e.g.:

``` typescript
    } catch(e) {
      if (e instanceof AbstractBindingError) e.addKey(binding.key);
      throw e;
    }
```

Becomes this:

``` dart
    } catch (e, e_stack) {
      if (e is AbstractBindingError) e.addKey(binding.key);
      rethrow;
    }
```

Where `e_stack` is unused.

**Comment by alexeagle** [comment]
I had looked into this when it came up on another bug, but it is hard to do.
Didn't we decide it's good to have the warning, because our typescript code should always reference e.stack?

**Comment by yjbanov** [comment]
We did, but I forgot about the rethrow case, so I reopened the issue.

**Comment by alexeagle** [comment]
Okay, right now our emit is simple and exactly follows the parse AST so
this is pretty hard. I'm going to punt for now. Let me or Martin know if
its urgent.

**Comment by yjbanov** [comment]
It's not urgent for ng2 because we can suppress these warnings. But these warnings will be popping up in users' builds, which will be very annoying. I'd say we should fix this for beta.

**Comment by alexeagle** [comment]
Why, do users re-build angular from sources?

**Comment by yjbanov** [comment]
That's how Dart works. It always compiles from sources.

**Comment by yjbanov** [comment]
It's similar to GWT and Closure in that respect.

**Comment by alexeagle** [comment]
We no longer use ts2dart
