### ISSUE TITLE
Avoid leading "./" when importing/exporting from a subdirectory

### ISSUE THREAD

**Issue by yjbanov** [angular/ts2dart#17]
```dart
library angular2.directives_dart;

export './src/directives/foreach.dart';
export './src/directives/if.dart';
export './src/directives/non_bindable.dart';
export './src/directives/switch.dart';
```

should be
```dart
library angular2.directives_dart;

export 'src/directives/foreach.dart';
export 'src/directives/if.dart';
export 'src/directives/non_bindable.dart';
export 'src/directives/switch.dart';
```

**Comment by mprobst** [comment]
Any particular reason why? I think the './' makes things more explicit and thus more readable.

**Comment by kevmoo** [comment]
This is the convention for dart code. We'd like to keep the generated code canonical.

**Comment by yjbanov** [comment]
@kevmoo Can we add it to the [style guide](https://www.dartlang.org/articles/style-guide/)? I thought I saw it in the past and I've been using this convention myself for a long time, but I don't see it in the style guide any more.
