### ISSUE TITLE
Insert some newlines

### ISSUE THREAD

**Issue by alexeagle** [angular/ts2dart#172]
We still have scenarios where angular build system spits out massive errors because of ts2dart output line length.
In particular, the dart formatter unhelpfully points out type errors in addition to formatting the code, so we don't have anything that just formats it first.
Seems like a reasonable fix is to emit newlines, like maybe after every curly brace and semicolon.

**Comment by mprobst** [comment]
@alexeagle, want to take a stab at this? It's a bit annoying as it requires changing a ton of test cases, I'm not entirely convinced it's worth it (though it'd be nice for our debugging, too).

**Comment by alexeagle** [comment]
Hasn't been an issue lately.
