### ISSUE TITLE
Support interface with properties

### ISSUE THREAD

**Issue by jelbourn** [angular/ts2dart#173]
I have an interface:
```ts
interface MdTabPart {
  protoViewRef: ProtoViewRef;
  elementRef: ElementRef;
}
```

Which results in this error:
```
Unsupported node type PropertySignature:   protoViewRef: ProtoViewRef;
Unsupported node type PropertySignature:   elementRef: ElementRef;
```

Seems like interface with properties just aren't dealt with presently.

@mprobst (I can't assign on this repo)

**Comment by jeffbcross** [comment]
Same. Why do you hate your users, @mprobst?

```
export interface Segment {
  name: string;
  regex: string;
}
```

**Comment by mprobst** [comment]
This is open source, the ultimate self service app! Just send a pull request ;-)

I'll get to this after the hackathon.
