### ISSUE TITLE
Remove forwardRef in ts2dart

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#177]
Dart does not have a forwardRef problem, and so you can have ts2dart just strip it out.

`forwardRef(()=>MyType)` becomes `MyType`.

example:

```javascript
directives: [
  bind(forwardRef(() => MyType).toClass(forwardRef(() => MyImpl),
  forwardRef(() => MyImpl)
]
```

becomes

```javascript
directives: [
  bind(MyType).toClass(MyImpl),
  MyImpl
]
```

**Comment by tbosch** [comment]
Closed via https://github.com/angular/ts2dart/commit/01f51f69d4c970a406babb3025bcc21e10860616
