### ISSUE TITLE
dart: initializer expression must be compile time constant

### ISSUE THREAD

**Issue by gdi2290** [angular/ts2dart#178]
when we use string interpolation in ts in our const constructor we need to convert it to string concats for dart const constructors to work properly.
for example
```typescript
@CONST
class Foo {
  baz: string;
  constructor(bar: string) {
    this.baz = 'Qux ${bar}';
  }
}
```
should output in dart
for example
```typescript
class Foo {
  final String baz;
  const Foo(String bar) : baz = 'Qux ' + bar + '';
}
```

please see
https://github.com/angular/angular/pull/2131#issuecomment-106915423

converting `OpaqueToken` to a const constructor I ran into a dart problem.

```
Internal error: 'package:angular2/src/di/opaque_token.dart': error: line 10 pos 36: initializer expression must be compile time constant.
    const OpaqueToken(String desc) : _desc = '''Token(${ desc})''';
```
I'm still having Dart const problems :/ here's my typescript `OpaqueToken`
```typescript
import {CONST} from 'angular2/src/facade/lang';
/**
 *
 *
 * @exportedAs angular2/di
 */
@CONST()
export class OpaqueToken {
  _desc: string;

  constructor(desc: string) { this._desc = `Token(${desc})`; }

  toString(): string { return this._desc; }
}

```
dart output
```dart
library angular2.src.di.opaque_token;

/**
 *
 *
 * @exportedAs angular2/di
 */
class OpaqueToken {
  final String _desc;
  const OpaqueToken(String desc) : _desc = '''Token(${ desc})''';
  String toString() {
    return this._desc;
  }
}

```

might be related
*  [dart/issues#19558](https://code.google.com/p/dart/issues/detail?id=19558)
*  [dart/issues#392](https://code.google.com/p/dart/issues/detail?id=392)

the fix was editing dart output to

```dart
library angular2.src.di.opaque_token;

/**
 *
 *
 * @exportedAs angular2/di
 */
class OpaqueToken {
  final String _desc;
  const OpaqueToken(String desc) : _desc = 'Token(' + desc + ')';
  String toString() {
    return this._desc;
  }
}
```

we could provide this workaround in ts2dart (I think this is where the changes should go [call.ts#L143](https://github.com/angular/ts2dart/blob/master/lib/call.ts#L143))

**Comment by mprobst** [comment]
ts2dart is intentionally a pretty dumb converter. Dumb is better as it leads to fewer unwelcome surprises. I think in this case the answer is simply to not do that, in particular as there is a simple workaround available with string concatenation in your TypeScript code to being with.

So the fix is either to teach Dart to recognize string interpolation literals as compile time constants, or to just use string concatenation in your TS code.
