### ISSUE TITLE
sourcemap for ts2dart includes local paths

### ISSUE THREAD

**Issue by alexeagle** [angular/ts2dart#180]
@vsavkin did the last ts2dart release, and his local paths (and username) appear in the published sourcemap (eg `build/lib/main.js.map`) on npm.
probably our gulpfile needs configure the sourcemaps differently (like here https://github.com/angular/ts2dart/blob/5e9638ca0b492ea38de19799f83db6ee7adb1395/gulpfile.js#L49)
@IgorMinar has some ideas about what to change

**Comment by mprobst** [comment]
I cannot reproduce. I can neither find @vsavkin's name in our source maps, nor does mine appear in a fresh build.

**Comment by alexeagle** [comment]
Rado, can you repro?

**Comment by rkirov** [comment]
Steps to repro:
```
npm i ts2dart
grep /Users/martinprobst node_modules/ts2dart/build/lib/base.js.map
```

**Comment by mprobst** [comment]
Doesn't on my recent build (`rm -r build ; gulp compile; grep /Users build/lib/*.map`). Maybe this was fixed by moving to a newer version of `gulp-typescript`?

**Comment by alexeagle** [comment]
I would guess you fixed it by adding the {base} property to the tsc options.

**Comment by mprobst** [comment]
But that was only for the test build?
