### ISSUE TITLE
Normalize slashes in createCompilerHost to support windows

### ISSUE THREAD

**Issue by piloopin** [angular/ts2dart#191]
In windows default path separator is backslash. Typescript internally normalizes slashes and converts them to /, so when it queries the host for getSourceFile, the sourceName won't match with the any entry in fileMap and hence the files don't get transpiled.

**Comment by piloopin** [comment]
Also getRelativeFileName in main.ts is not written to support windows.

**Comment by mprobst** [comment]
Good point. I don't have a Windows machine to easily test this on though, would you mind sending a PR for this?
