### ISSUE TITLE
Support protected members

### ISSUE THREAD

**Issue by btford** [angular/ts2dart#192]
I think what we really want to do here is use protected members: https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L38-L40

Works fine in JS, but Dart complains that "`Class 'RootRouter' has no instance getter '_registry'`."

Is there any way for ts2dart to support protected members?

/cc @jeffbcross

**Comment by mprobst** [comment]
I don't think Dart has `protected`, so we're out of luck here.
