### ISSUE TITLE
Array.concat

### ISSUE THREAD

**Issue by vicb** [angular/ts2dart#203]
JS concat takes several arguments, which can be either:
- Arrays -> `addAll`
- not Arrays -> `add`

The current implementation only support a single `Array` as argument

**Comment by mprobst** [comment]
Uh, that's nasty. I don't think we can reasonably distinguish parameters by type here, can we? We'd need a method on the Dart side that has the same semantics as concat, but we cannot easily express that, can we?

Maybe we could translate `x.concat(a, b)` to something like this (the function expression at the bottom):

```dart
main() {
  var x = ['some', 'list'];
  
  var a = [1];
  var b = 2;

  var y = (() { var tmp = new List.from(x);
           a is List ? tmp.addAll(a) : tmp.add(a);
           b is List ? tmp.addAll(b) : tmp.add(b);
           return tmp;} )();
  print(y);
}```

But that seems rather unwieldy for a simple `.concat()`. Alternatively we could give an error if we're not sure if `a` and `b` are lists and tell people to use `.push` or give better type information. I think this might be better than the function expression above, simpler and more predictable.

What do you think? Want to take a stab at this?

/cc @mhevery

**Comment by mhevery** [comment]
I don't think we should support the not Arrays use case. We should always just assume addAll takes an array, and throw if we can not verify it.

**Comment by mprobst** [comment]
@vicb do you want to take a stab at this? You could ask for `this.tc.getTypeAtLocation(arguments[i])` (for each argument) and check if the type is `Array`.

**Comment by vicb** [comment]
fixed via https://github.com/angular/ts2dart/pull/211
