### ISSUE TITLE
super invocation in constructor accessing members

### ISSUE THREAD

**Issue by vicb** [angular/ts2dart#207]
Seems like

```
class {
  constructor(args) {
    super(args);
}
```

get translated to

```
class {
  constructor(args): super(args);
}
```

which does not work when any args is structure like `public/private arg`

ie:

```
export class EmulatedScopedShadowDomStrategy extends EmulatedUnscopedShadowDomStrategy {
  constructor(public styleInliner: StyleInliner, styleUrlResolver: StyleUrlResolver, styleHost) {
    super(styleInliner, styleUrlResolver, styleHost);
  }

  // ...
}
```

This would fail with

```
dist/dart/angular2:[ERROR] Only static members can be accessed in initializers (/home/travis/build/angular/angular/dist/dart/angular2/lib/src/render/dom/shadow_dom/emulated_scoped_shadow_dom_strategy.dart, line 38, col 15)
      : super(styleInliner, styleUrlResolver, styleHost) {
               ^^^^^^^^^^^^
```

**Comment by mprobst** [comment]
That's a bit odd. `super(styleInliner)` should work, you're accessing a parameter, not a field. Could you give the complete Dart code that this is being transpiled to?

I'd expect something like this Dart code, and that (below) works:

```ts
class P {
  P(y);
}

class X extends P {
  String y;
  
  X(y): super(y);
}
```

**Comment by vicb** [comment]
I'll add more context next week but it seems like the issue is that when an arg is public or private in TS ctor arg, you will end up with super(this.argName) which is not supported in Dart because you can not use "this" in the initializer list.

**Comment by vicb** [comment]
```ts
class P {
  P(y);
}

class X extends P {
  constructor(public  y) {
    super(y);
  }
}

// ->

class P {
  P(y);
}

class X extends P {
  var y;
  
  X(this.y): super(y);
    
}

// -> Only static members can be accessed in initializers
```

**Comment by vicb** [comment]
When any parameter is used in the initialize list, you can not use `this.name` in the ctor argument.

This would work:

```
class P {
  P(y);
}

class X extends P {
  <type> y;

  X(<type> y): y = y, super(y); // note: your don't need to generate the longer "this.y = y"

}
```

**Comment by mprobst** [comment]
@alexeagle I think you understand more of this than I do, maybe something for you?

**Comment by alexeagle** [comment]
Sure will look Monday

**Comment by alexeagle** [comment]
obsolete
