### ISSUE TITLE
Travis is flaky

### ISSUE THREAD

**Issue by vicb** [angular/ts2dart#226]
due to [403](https://travis-ci.org/angular/ts2dart/builds/68453950#L160)

is there anything we can do to improve the situation ?

/cc @mprobst

**Comment by mprobst** [comment]
This is due to github rate limiting `tsd`. I think we should be able to fix this with a `TSD_GITHUB_TOKEN` in `.travis.yml`. See (here)[https://github.com/DefinitelyTyped/tsd#tsdrc].

@vicb want to take a stab at it?

**Comment by vicb** [comment]
Thanks for the pointer.

However it seems we already have this setup https://github.com/angular/ts2dart/blob/master/.travis.yml#L20

Looking at why it doesn't work ATM

**Comment by mprobst** [comment]
Maybe we should be using the environment variable `TSD_GITHUB_TOKEN`, not `TSDRC`?

**Comment by mprobst** [comment]
Let's hope that fixes it. If not, we can try not having `tsd` replace the existing files (less traffic), or the `.tsdrc` way. Kind of nasty to debug and figure out if a solution is correct...
