### ISSUE TITLE
add support for XMLHttpRequest to base.ts (use HttpRequest in Dart)

### ISSUE THREAD

**Issue by jeffbcross** [angular/ts2dart#230]

**Comment by mprobst** [comment]
@jeffbcross what do you mean exactly by support exactly? `XMLHttpRequest` AFAIK has an API that's very different from `HttpRequest` in Dart. As `XMLHttpRequest`s API is famously wonky, it'd IMHO be better to just introduce a platform specific abstraction.

That is, have a `http_request.ts` for JavaScript that wraps `XMLHttpRequest` in a sane API, and (in the same place) `http_request.dart` that does the same for Dart. Both should export the same symbols/API, and then for Dart the `.dart` gets substituted transparently.

**Comment by jeffbcross** [comment]
Sorry, I opened this during a code review and should've added more detail.

The APIs are actually very similar, and I have an abstraction already ([ts](https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/browser_xhr.ts), [dart](https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/browser_xhr.dart)), but I am forced to use ["any" type](https://github.com/angular/angular/blob/5b5ffe75d0d1a3ac6204114203d8d566d49e9c70/modules/angular2/src/http/backends/xhr_backend.ts#L27) on the fields to which instances are assigned. 

I

**Comment by mprobst** [comment]
I see, that's a valid use case (and a bit surprising on the Dart side, why would you emulate `onReadyStateChange`?).

Send a PR to add the type renaming?

Also note that the `declare var window;` in the code you linked to above is superfluous, AFAICT.

**Comment by jeffbcross** [comment]
Sounds good, will open a PR. And will remove the window declaration.

**Comment by mprobst** [comment]
This has been done.
