### ISSUE TITLE
clang format returns inconsistent results locally vs Travis

### ISSUE THREAD

**Issue by vicb** [angular/ts2dart#233]
see https://github.com/angular/ts2dart/pull/225

The PR is fine on Travis while it fails on my machine (the file reported has unformatted is not touched by the PR - I have `rm node_modules -rf` & `npm i`)

There is someting wrong with clang-format.

/cc @mprobst

**Comment by mprobst** [comment]
I think this is likely Travis' `clang-format` being out of date. According to your comment you're using `1.0.25`, but there's nothing forcing `clang-format` to be upgraded on Travis. I'll TAL at using the new ability to pass in a specific `clang-format` version.

**Comment by mprobst** [comment]
This has been fixed.
