### ISSUE TITLE
Many "experimentalDecorators" warnings appear if anything goes wrong during ts2dart

### ISSUE THREAD

**Issue by jeffbcross** [angular/ts2dart#242]
For example, I had an untyped property access error, that caused ts2dart to create a huge log of warnings like this one for every decorator instance in angular.

`examples/src/zippy_component/zippy.ts:10:14: Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.`

I have to scroll up several pages to see the actual warning.

**Comment by mprobst** [comment]
See #241
