### ISSUE TITLE
[ERROR] Undefined class 'HttpRequest'

### ISSUE THREAD

**Issue by alfonso-presa** [angular/ts2dart#245]
When trying to use XmlHttpRequest in TS, when using ts2dart it tell's HttpRequest is not found. It was included here: https://github.com/angular/ts2dart/pull/232, but look's like it's not correctly adding the `import 'dart:html';` when needed.

I've been trying to solve it myself to PR but I have no clue on how to trigger the import emit. I you give me some hints I can try to do it :-).

Thanks!

**Comment by mprobst** [comment]
Fixed by 6d5ed11.
