### ISSUE TITLE
support decorators on top-level fields

### ISSUE THREAD

**Issue by sigmundch** [angular/ts2dart#249]
To support Dart transformers in angular2, we need to generate a Dart annotation on a top-level field declaration.

Adding the following test would validate what we need:
```diff
diff --git a/test/decorator_test.ts b/test/decorator_test.ts
index 837d374..16950f8 100644
--- a/test/decorator_test.ts
+++ b/test/decorator_test.ts
@@ -15,6 +15,8 @@ describe('decorators', () => {
      () => { expectTranslate('@A function f() {}').to.equal(' @ A f ( ) { }'); });
   it('translates on properties',
      () => { expectTranslate('class X { @A p; }').to.equal(' class X { @ A var p ; }'); });
+  it('translates on top-levels',
+     () => { expectTranslate('@A var p;').to.equal('@ A var p;'); });
   it('translates on parameters',
      () => { expectTranslate('function f (@A p) {}').to.equal(' f ( @ A p ) { }'); });
   it('special cases @CONST', () => {
```

**Comment by mprobst** [comment]
TypeScript doesn't support decorators on fields; you can only decorate Function objects (i.e. functions, constructors, and methods).

Can  you expand on what the requirement/use case is for this? Maybe there's a different way to implement this.

**Comment by sigmundch** [comment]
mmm - I'm working on a fix for https://github.com/angular/angular/issues/1747 (support for directive-aliases in Dart transformers). My fix requires that users decorate the directive aliases with an annotation. I was able to make this work in plain Dart, and as a final part of my change I started migrating my changes to the original sources in typescript. That's when I realized we weren't generating these.

You should be able to see what I'm trying to do in this "diff" view (I haven't sent the PR out yet): https://github.com/angular/angular/compare/master...sigmundch:expand_meta?expand=1

The 3rd file in that diff (`directives.ts`) shows where I'm trying to annotate the top-level declaration.

I noticed that the parser does include the decorators in the VariableStatement node, so I was able to get the test passing if I do this change in the ts2dart compiler:

https://github.com/angular/ts2dart/compare/master...sigmundch:add_decorator_on_top_level?expand=1

WDYT?

**Comment by mprobst** [comment]
I'm afraid I don't understand enough about the use case to have a qualified comment on this. Why do you need the annotation in the first place, to transport reflection metadata to dart2js? Why is it not enough to just pass an array there?

TypeScript's parser generally tries to produce a working AST for all kinds of broken input, but I think there are no working semantics for directives on a `var` (i.e. what's the object that you would decorate? `var` declarations have no representation at runtime). So that likely won't change, and obviously Angular has to compile as valid TypeScript.

**Comment by sigmundch** [comment]
> Why do you need the annotation in the first place, to transport reflection metadata to dart2js?

Practically yes. It is mainly to mark constants that the dart2dart transformer needs to pay attention to. 

> what's the object that you would decorate?

The enclosing scope?


The reality is that we don't need a representation for the annotation at runtime though. Is there anything in TypeScript resembling a compile-time only annotation?

**Comment by mprobst** [comment]
>
> Why do you need the annotation in the first place, to transport reflection
> metadata to dart2js?
>
> Practically yes. It is mainly to mark constants that the dart2dart
> transformer needs to pay attention to.
>
Do we need that? We only expect to use the Dart VM for development, right?
When do we need to minify dart code into dart code?


>  what's the object that you would decorate?
>
> The enclosing scope?
>
Scopes don't have a runtime representation in JavaScript, either.

> The reality is that we don't need a representation for the annotation at
> runtime though. Is there anything in TypeScript resembling a compile-time
> only annotation?
>
No. What we could do is have a special-cased function that triggers the
annotation, similar to CONST_EXPR, and then only include the annotation in
Dart code. Or could you just special case a particular function call in
dart2dart?

Martin

>

**Comment by sigmundch** [comment]
> Do we need that? 

Sorry for the confusion about "dart2dart" - I shouldn't have used that overloaded term. I am referring to the angular2 transformer, which just happens to be a dart 2 dart transpiler that eliminates all uses of reflection in DI and replaces it with code dart2js can compile better.

>> The enclosing scope?
> Scopes don't have a runtime representation in JavaScript, either.

Sorry bad terminology again - I'm thinking of the implicit `this` object that holds global variable declarations (commonly `window`).

> What we could do is have a special-cased function that triggers the
annotation, similar to CONST_EXPR, and then only include the annotation in
Dart code.

This might be a good option for us - the alternative I was considering was to change:

```dart
@A
const foo = const [...]
```

into:
```dart
const foo = const A(const [...]);
```

I like the idea of something similar to CONST_EXPR so that we don't pay for any runtime cost for this compile-time only requirement.

**Comment by mprobst** [comment]
Using a marker function like this:

```ts
const foo = const A(const [...]);
```

... seems like a reasonable thing to do. I wonder if we even need to special case/handle this in `ts2dart`. `A` would be the identity function, so I'd expect that `dart2js` trivially inlines it, and we'd never pay any runtime cost for it outside of development. And even in development this should hopefully not matter much, this is after all code that only runs once on startup, should never be a performance bottleneck, and even if so, your VM should inline.

**Comment by sigmundch** [comment]
> Using a marker function like this:
```dart
const foo = const A(const [...]);
```

Actually, I was suggesting we use a const constructor of a class, rather than a function call. Otherwise we can't use the value of `foo` within an annotation.

This would add a wrapper object in a few places, but it's not a big deal IMO.

**Comment by sigmundch** [comment]
Thanks again for the feedback - I agree that unless TS adds support for decorators at top-level variable declarations, we shouldn't add it here.

I'll close the bug for the time being.

**Comment by mprobst** [comment]
Thanks @sigmundch for the insight, I agree that sounds like a good solution.
