### ISSUE TITLE
`Map.forEach` calls the callback with `(key, value)`, but in JavaScript it's `(value, key)`

### ISSUE THREAD

**Issue by tbosch** [angular/ts2dart#253]

**Comment by mprobst** [comment]
#215 is trying to fix that, but @vicb is AFAIK currently busy moving to the US.

**Comment by vicb** [comment]
We arrived yesterday.
I should be able to start contributing again sometime next week.

**Comment by mprobst** [comment]
Welcome! And no worries, I hope it's not too urgent. I can also take over
the change if you want to?

Victor Berchet <notifications@github.com> schrieb am Fr., 31. Juli 2015 um
09:50 Uhr:
