### ISSUE TITLE
decouple from angular

### ISSUE THREAD

**Issue by jeffbcross** [angular/ts2dart#267]
It would be nice to be able to parameratize some things that are hard-coded and angular-specific, if for nothing else, to make it easier to refactor angular without having to change ts2dart. For example, #266 is a necessary change to hard-coded paths because the angular project is being re-organized.

**Comment by jeffbcross** [comment]
@alexeagle volunteered to do all the work

**Comment by mprobst** [comment]
I think this has been done, ts2dart is now used in Angular Material.
