### ISSUE TITLE
Array.forEach facade produces invalid code

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#272]
```
var a = [];
a.forEach((k, v) => { stmt1(); });
```

produces  in dart
```
a.forEach((k, v) => { stmt1(); });
```

this is incorrect, since `=>` and `{}` can not be used together. Valid outputs would either of these:
```
a.forEach((k, v) { stmt1(); });
a.forEach((k, v) => stmt1();});
```

**Comment by vicb** [comment]
Not sure what's going wrong here, there is no special case for this one (i.e. any arrow function should be translated by ts2d whatever the context).

But you probably want to have a single argument for the cb - the item.

**Comment by jsayol** [comment]
Just FYI, ts2dart already produces the correct output now ( `a.forEach((k, v) { stmt1(); });` ) so this issue can be closed.

**Comment by mprobst** [comment]
Thanks for pointing this out.
