### ISSUE TITLE
Array.concat does not work

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#273]
```
_injectorBindings(appComponentType).concat(bindings)
```

produces:

```
new List . from( _injectorBindings( appComponentType)) .. addAll (bindings)
```

notice the `..`

**Comment by vicb** [comment]
`..` is here to return the `List` as JS does.

**Comment by vicb** [comment]
However we should probably enclose the expression in parenthesis, as `(new List.from(...).addAll(...)).length` would not work without them.

Is this your issue ?

**Comment by mhevery** [comment]
@vicb you are right. I think the issue is that the extra spaces confuse the formatter. Maybe parents would help here?

**Comment by vicb** [comment]
Could you provide the full unformated function so that I can check and add the parents if they help ?

**Comment by mhevery** [comment]
this happens when translating `[].concat([])`

**Comment by vicb** [comment]
I can not reproduce here, it would translate to `new List . from ( [ ] ) .. addAll ( [ ] ) ;` which `dartfmt` seems to be able to handle successfully (at least with SDK 1.12) - I'll submit a PR anyway.
