### ISSUE TITLE
Support generics on methods

### ISSUE THREAD

**Issue by tbosch** [angular/ts2dart#282]
It would be nice to write something like this:

```
function add<NUM>(a:NUM):NUM {...}
```

and have the following in Dart:
```
/*<NUM>*/ add/*<NUM>*/(/*<NUM>*/ a){...}
```

This is needed in Angular e.g. for [`ViewContainerRef.createEmbeddedView`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/linker/view_container_ref.ts#L66):
I would like to write this:
```
createEmbeddedView<C>(templateRef: TemplateRef<C>, context?: C,
                              index?: number): EmbeddedViewRef<C>
```

But right now ts2dart outputs this:
```
EmbeddedViewRef<C> createEmbeddedView/*< C >*/(TemplateRef<C> templateRef,
      [C context, num index]);
```

The tricky bit here is that this output of ts2dart would be correct if `ViewContainerRef` had a generic `C` declared on itself (e.g. `class ViewContainerRef<C> { ...}`). However, in this case, the generic originates just from the method itself.

**Comment by yjbanov** [comment]
Dart has temporary syntax for generic methods now that we should be able to emit TypeScript generic methods/functions/typedefs to. Let's do that.

**Comment by mprobst** [comment]
@yjbanov do you have a pointer to docs?

**Comment by yjbanov** [comment]
@jacob314 might have some

**Comment by jacob314** [comment]
https://github.com/dart-lang/dev_compiler/blob/a1b57501c1528b7573f807e076e0b02aa83e5d35/GENERIC_METHODS.md

**Comment by tbosch** [comment]
@mprobst Hi, could you have a look at this?

**Comment by mprobst** [comment]
This is supported since quite a bit, it'll translate generic parameters on methods into Dart DDC's comment syntax.

**Comment by tbosch** [comment]
Just checked with the current version. If I write
```
createEmbeddedView<C>(templateRef: TempalteRef<C>, context: C, index: number):EmbeddedViewRef<C>
```

I am getting this:
```
EmbeddedViewRef<C> createEmbeddedView/*< C >*/(TemplateRef<C> templateRef,
      [C context, num index]);
```
