### ISSUE TITLE
Remove brackets from computed properties of classes

### ISSUE THREAD

**Issue by jeffbcross** [angular/ts2dart#304]
In issue https://github.com/angular/angular/issues/5036 on angular/angular, we want to use Es6 `Symbol` as computed properties to denote Lifecycle hooks on component classes. Since we'll export the symbols as names that match the appropriate interface names in the dart interfaces, we could just drop the square brackets in the classes.

Source:
```typescript
import {OnInit} from 'lifecyclehooksinterfaces'
import {onInit} from 'lifecyclesymbols';
class MyComponent implements OnInit {
  [onInit]() {
  }
}
```

After transpilation:
```dart
import {OnInit} from 'lifecyclehooksinterfaces'
class MyComponent implements  OnInit {
  onInit () {    
  }
}
```

This approach would not be a very good general-purpose solution to computed properties.

CC @vsavkin @IgorMinar

**Comment by alexeagle** [comment]
What's the status of this design? Did Misko convince you to do something different?
pls assign back to me when you're sure you want this...

**Comment by jeffbcross** [comment]
I'm going to spike the implementation that uses computed properties in JS, but without using actual symbols. We'll see if anything is required of ts2dart. I'll actually close this for now, until I have a better idea if/what ts2dart would need to do.
