### ISSUE TITLE
relative path to stdlib changed

### ISSUE THREAD

**Issue by alexeagle** [angular/ts2dart#314]
When we run latest ts2dart from angular, we don't convert the facade methods.
The facade_converter has a map from filename to the types we understand, one such filename is "lib"
with the current ts2dart we instead see "../../lib".
Looks like this was introduced in https://github.com/angular/ts2dart/commit/4ae749e597303b7606d647b23daed1463943bc59#diff-dfc2e8680f99b78f2e7d8c13b9a44855L249

I'm going to restore that conditional check to un-block angular. @vikerman this might break the g3 usage?

**Comment by alexeagle** [comment]
// @IgorMinar

**Comment by vikerman** [comment]
Oops. I tested my ts2dart changes with Angular 2 sources to make sure the code was generated without errors but did not run all the Dart tests.

g3 has a local change patching paths for different filenames and will have to manually patched each time till we refactor that part out.
