### ISSUE TITLE
support function types

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#358]
Given:
```
  method(fn: (V, K) => void) { ... }
```

Expected:
```
  method(void fn(V arg0, K arg1)) { ... }
```

Actual:
```
  method(dynamic /* (V, K) => void */ fn) { ... }
```

/cc: @vsmenon

**Comment by mprobst** [comment]
How does this interact with generic method types? `f/*<A, B>*/(dynamic/*=B*/ fn(dynamic/*=A*/ a) )`?

How does this look for recursive types?

**Comment by vsmenon** [comment]
That looks correct on generics.

Here's an example with function typed arguments:
```
void foo(String bar(String baz())) {
  var result = bar(() => "hello");
  print(result);
}
```
