### ISSUE TITLE
Compile rest parameters to untyped Function objects

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#360]
Given:
```
method(fn: (..._: any[]) => Promise<any>| void,){...}
```
Expect:
```
method(Function fn){...}
```
Got Error:
```
Compile rest parameters to untyped Function objects
```

**Comment by mprobst** [comment]
The returned union type should get transformed into a `dynamic /* ... */` comment, right?

I can take a look tomorrow, happy for somebody else to pick this up earlier if they have time.

**Comment by mhevery** [comment]
Correct

**Comment by mprobst** [comment]
I assume the fix you ask for is to de-generate all function parameters that have varargs/rest parameters into just `Function`.

I don't think you got that code as an error, what you should have gotten is: `rest parameters are unsupported`. It'd be nice if you could write up the actual error you get, that'd be a lot less puzzling :-)

**Comment by mhevery** [comment]
Sorry. Yes it throws `Compile rest parameters to untyped Function objects`

**Comment by mhevery** [comment]
thank you.
