### ISSUE TITLE
Unnecessary cast

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#362]
Given:
```
0x22 | 0xF0
```

Expected:
```
0x22 | 0xF0
```

Actual:
```
(0x22 as int) | (0xF0 as int)
```

The reason we add casting is because it is required in this case
```
var a = 0x22;
var b = 0xF0;
a | b
```

because Typescript makes `a` and `b` a number, which does need to be down casted to an `int`.

**Comment by mprobst** [comment]
Fixed.
