### ISSUE TITLE
Cannot have multiple groups of positional parameters in a single parameter list

### ISSUE THREAD

**Issue by alexeagle** [angular/ts2dart#58]
input:
 constructor(bindings:List, parent=null, defaultBindings=false) {

line 1, column 966 of dist/dart.ts2dart/injector.dart: Cannot have multiple groups of positional parameters in a single parameter list
...
Injector ( List bindings , [ parent = null ] , [ defaultBindings = false ] )

**Comment by alexeagle** [comment]
Martin, are you still working on this one?

**Comment by mprobst** [comment]
Yes, I have a half-baked CL that was waiting for your change to go in. Give me 30 mins :-)
