### ISSUE TITLE
Escape \u sequences properly (angular2/src/change_detection/parser/lexer.dart)

### ISSUE THREAD

**Issue by mprobst** [angular/ts2dart#79]

**Comment by alexeagle** [comment]
Is the issue here that the original source isn't valid TS?
https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/parser/lexer.js#L375
doesn't seem to work:
http://www.typescriptlang.org/Playground#src=var%20code%20%3D%201234%3B%0Avar%20str%20%3D%20%60%5Cu%24%7Bcode%7D%60%3B%0A

**Comment by mprobst** [comment]
I think the intention of the code is to produce a literal `\u1234` output, so I think the issue is that we loose the double escaping of the \u. This is what's intended and it works:

http://www.typescriptlang.org/Playground#src=var%20code%20%3D%201234%3B%0Avar%20str%20%3D%20%60%5Cu%24%7Bcode%7D%60%3B%0A

**Comment by alexeagle** [comment]
TypeScript requires double-backslashing. So this works:
```
expectTranslate("`[\\\\u${hex}]`").to.equal(" '''[\\u${ hex}]''' ;");
```
but if we make that change in the Angular code, we'll get an extra backslash printed. That's probably okay since it's just an error message, but I'm checking w/ TypeScript to see if this is expected.

**Comment by alexeagle** [comment]
This is probably fixed by TypeScript at HEAD. Let's hold this issue until we have a release from them.

**Comment by mprobst** [comment]
This is actually a bug in our code, we're taking the post-escaped Node.text value and just dump it into the string without escaping escape sequences in it. See my pull request.
