### ISSUE TITLE
Handle façades for Dart code (native implementations of some functionality in dart)

### ISSUE THREAD

**Issue by mprobst** [angular/ts2dart#85]

**Comment by alexeagle** [comment]
Can you clarify what is needed, or a problem to repro?
Seems to me the facade layer is already in dart, so it just needs to be copied to the dist folder?

**Comment by mprobst** [comment]
Yeah, but how is TS going to understand it, and compile the code correctly?
Do we need to write .d.ts files for this? Do we put the .js implementations
through TS? If so, how do we make sure we don't compile them to Dart?

Alex Eagle <notifications@github.com> schrieb am Di., 24. März 2015 um
15:35 Uhr:

**Comment by mprobst** [comment]
The resolution of this was having `.dart` files for platform specific façades, and have those shadow `.ts` files with the same name. This is implemented in the broccoli and gulp drivers for ts2dart.
